README.md
src/cf-definitions-builder.ts
src/index.ts

By default we remove or/and ensure the output folder.
If this behaviour is not wanted, we can preserve an existing output folder and override existing files.

feat(cli): flag to preserve output folder

---

src/cf-property-types.ts
src/renderer/cf-render-prop-array.ts
src/renderer/cf-render-prop-link.ts
src/utils.ts
test/cf-render-prop.test.ts

It is possible that the `validations` on an entity field can be undefined, leading to type errors. This change adds guards to avoid this situation.
Resolves #18

Add guards for potentially undefined field

---

src/cf-definitions-builder.ts
src/cf-property-imports.ts
test/cf-definitions-builder.test.ts

When a type references itself in one of the fields, no self referencing imports should be added.
Fixes #19

fix(imports): self references

---

src/index.ts

Use env var `CTF_CMA_TOKEN` as default for CMA token.
This will ease using this tool inside package.json `scripts` block without exposing the CMA token.

feat(credentials): use env var as default token

---

src/cf-definitions-builder.ts
test/cf-definitions-builder.test.ts

export index (barrel) file with `isTypeOnly` flag.
**Before:**
```typescript
export { TypeSysId, TypeSysIdFields } from "./TypeSysId";
```
**After:**
```typescript
export type { TypeSysId, TypeSysIdFields } from "./TypeSysId";
```

fix(export): types only export for index file

---

src/renderer/generic/render-type-union.ts
test/renderer/field/render-prop-any.test.ts
test/renderer/field/render-prop-array.test.ts

We don't want to rely on the deterministic behavior of contentful export and how the content is created. This change ensures union types are always rendered in the same order. 
The changes in the tests are reflecting this behavour.
solves: #155

fix: union order to ensure deterministic output

---

src/renderer/generic/render-type-array.ts

If the `renderTypeArray` renders a union of types, only the last type would be an array. 
Before this change an array of a union type would render like this:
```
Foo | Bar[]
```
After this change an array of a union type would render like this:
```
(Foo | Bar)[]
```

🐛 Fix renderTypeArray to handle unions

---

src/renderer/field/render-prop-array.ts
src/renderer/generic/render-type-array.ts

Hey @tatemz, 
your change caused several tests to fail (just realised I didn't run them on your PR 🤦 )
I partially changed it back and added a guard back to ensure the `(` `)` in the right place. 
Would be good to know if this also solves your issue :)

fix: rendering arrays of unions

---

src/cf-definitions-builder.ts

A common use case of CFDefinitionsBuilder would be to fetch all content types using `environment.getContentTypes()` and pass it along. Then, you need to manually add types one by one, instead of passing it all at once. This method makes it easier.

feat: add appendTypes() method

---

src/cf-definitions-builder.ts

When using in browser environment, node dependency crashes the build

fix: remove node depedency from builder [NONE]

---

README.md
package.json
src/cli.ts
src/index.ts
src/renderer/type/index.ts
src/renderer/type/js-doc-renderer.ts
test/renderer/type/js-doc-renderer.test.ts
yarn.lock

Adds new JSDoc renderer to enrich types with JSDoc comments. 
When used "as code", the renderer can be fully configured through options. 
Can be used via CLI with flag `--jsdoc`

feat: add new JSDoc renderer

---

README.md
src/renderer/type/js-doc-renderer.ts
test/renderer/type/js-doc-renderer.test.ts

Add JSDocs for field-level comments.

feat: introduce field level comments

---

README.md
src/cli.ts
src/index.ts
src/property-imports.ts
src/renderer/field/render-prop-any.ts
src/renderer/field/render-prop-array.ts
src/renderer/field/render-prop-link.ts
src/renderer/field/render-prop-richtext.ts
src/renderer/type/default-content-type-renderer.ts
src/renderer/type/localized-content-type-renderer.ts
test/cases/fixtures/01-output.txt
test/cf-definitions-builder.test.ts
test/property-imports.test.ts
test/renderer/field/render-prop-any.test.ts
test/renderer/field/render-prop-array.test.ts
test/renderer/field/render-prop-link.test.ts
test/renderer/field/render-prop-richtext.test.ts
test/renderer/type/content-type-renfderer.test.ts
test/renderer/type/js-doc-renderer.test.ts
test/renderer/type/localized-content-type-renfderer.test.ts

- Switch to named imports for all types of `contentful` to ensure we only import type information.
- switch to type imports to aline with Typescript's latest defaults
Fixes https://github.com/contentful-userland/cf-content-types-generator/issues/163

feat: switch to named imports

---

src/cf-definitions-builder.ts
src/renderer/type/type-guard-renderer.ts
test/cf-definitions-builder.test.ts
test/renderer/type/type-guard-renderer.test.ts

`TypeGuardTypes`  were not properly presented in single file output

fix: type guard types in merge file [NONE]

---

README.md
src/renderer/field/render-prop-richtext.ts
test/renderer/field/render-prop-richtext.test.ts

`CFRichTextTypes` does not contain `RichText` type.
I believe the intention of https://github.com/contentful-userland/cf-content-types-generator/pull/106 was to use `EntryFields` imported from `contentful` instead.

fix: import RichText from contentful

---

src/cf-definitions-builder.ts
test/cf-definitions-builder.test.ts

We can't export type guard functions as types. 
fixes https://github.com/contentful-userland/cf-content-types-generator/issues/237

fix: exports of type guards

---

package.json
src/extract-validation.ts
src/property-imports.ts
src/renderer/field/default-renderers.ts
src/renderer/field/index.ts
src/renderer/field/render-prop-any.ts
src/renderer/field/render-prop-array.ts
src/renderer/field/render-prop-link.ts
src/renderer/field/render-prop-resource-link.ts
src/renderer/field/render-prop-richtext.ts
src/renderer/field/render-types.ts
src/renderer/type/create-default-context.ts
src/renderer/type/default-content-type-renderer.ts
src/renderer/type/js-doc-renderer.ts
src/types.ts
test/renderer/field/render-prop-array.test.ts
test/renderer/field/render-prop-resource-link.test.ts
test/renderer/type/content-type-renfderer.test.ts
yarn.lock

Add basic support for `ResourceLink` fields to address https://github.com/contentful-userland/cf-content-types-generator/issues/198 and update contentful.js to v10 because resource link support in v9 is slightly broken.
This version doesn’t add types for content types linked in `ResourceLink` fields as that would require a bigger change to fetch content types from multiple spaces.

feat: support resource link fields

---

README.md
src/cli.ts
src/module-name.ts
src/renderer/field/index.ts
src/renderer/field/render-prop-any.ts
src/renderer/field/render-prop-array.ts
src/renderer/field/render-prop-link.ts
src/renderer/field/render-prop-resource-link.ts
src/renderer/field/render-prop-richtext.ts
src/renderer/field/v10-renderers.ts
src/renderer/generic/render-type-generic.ts
src/renderer/type/create-v10-context.ts
src/renderer/type/index.ts
src/renderer/type/js-doc-renderer.ts
src/renderer/type/v10-content-type-renderer.ts
src/renderer/type/v10-type-guard-renderer.ts
test/renderer/field/render-prop-any.test.ts
test/renderer/field/render-prop-array.test.ts
test/renderer/field/render-prop-link.test.ts
test/renderer/field/render-prop-resource-link.test.ts
test/renderer/field/render-prop-richtext.test.ts
test/renderer/type/content-type-renderer.test.ts
test/renderer/type/js-doc-renderer.test.ts
test/renderer/type/v10-content-type-renderer.test.ts

Add `--v10` option to generate types compatible with contentful.js v10.
* Add new renderer for v10 types
* Add new renderer for v10 type guards
* Update JsDoc renderer to support new skeleton type
* Add `--v10` option to switch to v10 renderer
* Support combining other options with `--v10` (except for `--localized` which is redundant and throws error)
```typescript
import type { ChainModifiers, Entry, EntryFieldTypes, EntrySkeletonType, LocaleCode } from "contentful";
export interface TypeAllFieldsFields {
richText?: EntryFieldTypes.RichText;
symbol?: EntryFieldTypes.Symbol;
symbolWithValues?: EntryFieldTypes.Symbol<"option a" | "option b">;
symbolList?: EntryFieldTypes.Array<EntryFieldTypes.Symbol>;
symbolListWithValues?: EntryFieldTypes.Array<EntryFieldTypes.Symbol<"option a" | "option …
```

feat: add support for contentful.js v10

---

src/cli.ts
src/renderer/type/index.ts

Add missing top-level export for `V10TypeGuardRenderer`

fix: top level export for v10 typeguard

---

src/property-imports.ts
src/renderer/type/create-default-context.ts
src/renderer/type/create-v10-context.ts
src/renderer/type/default-content-type-renderer.ts
test/renderer/type/content-type-renderer.test.ts
test/renderer/type/js-doc-renderer.test.ts
test/renderer/type/v10-content-type-renderer.test.ts

Fixes https://github.com/contentful-userland/cf-content-types-generator/issues/249. The v10 renderer provided relative imports for the field type despite only using the skeleton type in links.
* Change provided imports from field type to skeleton type in v10 context
* Simplify imports for the v9 renderer (same as v10 already does)
* Add tests for both v9 and v10 imports.

fix: import skeleton for links in v10 types

---

package.json
patches/contentful+10.1.8.patch
src/extract-validation.ts
test/extract-validation.test.ts
yarn.lock

For legacy reasons, `ContentTypeFieldValidation`'s field `linkContentType` can also just be of type `string`.
Fixes #148

fix: linked content type validations [NONE]

---

.eslintignore
test/cases/case-01.test.ts
test/cf-definitions-builder.test.ts
test/extract-validation.test.ts
test/module-name.test.ts
test/renderer/type/content-type-renderer.test.ts
test/renderer/type/js-doc-renderer.test.ts
test/renderer/type/localized-content-type-renfderer.test.ts
test/renderer/type/v10-content-type-renderer.test.ts

I realised that `test` was for some reason excluded from linting, so I have changed that and fixed things as needed - there are a few changes that are better addressed in other ways like adding missing type properties but they should be done in dedicated PRs

refactor: apply linting to tests

---

README.md

Current documentation wasn't correct how to set a target directory where the files are stored. Additionally when using existing folder its contents are wiped out.

chore: Update readme for target directory

---

src/cf-definitions-builder.ts
src/commands/index.ts
src/renderer/type/content-type-renderer.ts
src/renderer/type/js-doc-renderer.ts
src/types.ts
test/renderer/type/js-doc-renderer.test.ts

Add field help texts to generated JSDoc comments. The help text is added as a new [`@summary`](https://jsdoc.app/tags-summary) tag so that the existing functionality is not changed in a breaking way. For example:
```ts
export interface TypePageFields {
/**
* Field type definition for field 'name' (Name)
* @name Name
* @localized false
* @summary Internal name, not visible to users.
*/
name: EntryFieldTypes.Symbol;
```
The tag is only added if the field has a help text.
See related issue: https://github.com/contentful-userland/cf-content-types-generator/issues/290

feat: Add field help texts to generated JSDoc

---

package.json
src/commands/index.ts
src/renderer/type/default-content-type-renderer.ts
src/renderer/type/v10-content-type-renderer.ts
test/cf-definitions-builder.test.ts
test/property-imports.test.ts
yarn.lock

Update oclif related dependencies
(marked as `fix` to trigger a release)

fix: bump oclif dependencies

---

README.md
bin/dev
bin/run
src/commands/index.ts
src/renderer/type/response-type-renderer.ts
test/renderer/type/localized-content-type-renfderer.test.ts
test/renderer/type/response-type-renderer.test.ts
tsconfig.json

The currently generated types only work as input types and as response type for the default chain modifiers. for all other combinations of the chain modifiers, we can create dedicated types. 
Solves: https://github.com/contentful/contentful.js/issues/2138#issuecomment-1921923508

feat: add response type renderer

---

src/renderer/type/type-guard-renderer.ts

The generated `is{entryName}` functions are only useful if you're confident that the thing you're passing in is, at least, a fully-fleshed-out `Entry` type. But it's possible to not know what exactly you have. In my case, I have a situation where my object is either a string, an unresolved link, or one of three entry types. And in that case the caller of `is{entryName}` will need to do additional checks to make sure it's even safe to call this function, or risk throwing an exception. Better to have the function just behave safely and do its job all the way.
As a general practice in TS, `isXYZ` functions should be safe to call with any argument.

use optional chaining in the type guard for greater safety

---

package.json
yarn.lock

Noticed that v4 has some breaking changes that we do not yet cover in our tests. There is also no clear migration get yet, so we will downgrade for now and investigate further.
fixes: https://github.com/contentful-userland/cf-content-types-generator/issues/363

fix: downgrade oclif to v3

---

package.json
src/renderer/field/render-prop-resource-link.ts
test/renderer/field/render-prop-resource-link.test.ts
yarn.lock

Trying to use `cf-content-types-generator` with a Contentful schema that includes fields with native external references currently results in an exception and failure to generate types. This PR updates `renderPropResourceLinkV10` to recognize the `ExternalResourceLink` type and allow it. When encountering an unknown `allowedResources` value it logs the value and treats it as `EntryFieldTypes.ExternalResourceLink`. Includes updated tests.

feat: accept resource links to native external references in v10 type generator

---

src/renderer/generic/render-type-literal.ts
test/rendered/generic/render-type-literal.test.ts

Fixes #415 
Use `JSON.stringify` to render string literals.
This means that e.g. if you have a string `"a\nb"` when it's rendered into the output Typescript instead of 
```
"a
b"
```
which is a syntax error, you will get
```
"a\nb"
```
as desired, and so on for other sequences that should be escaped when serialising a string.

fix: stringify string literals correctly
