.github/workflows/semantic-release.yml
.github/workflows/test.yml
README.md
package.json

Create coverage reports and add report as PR comment

feat(chore): add coverage reports

---

README.md
package.json
src/utils.ts
test/cf-definitions-builder.test.ts
test/cf-property-imports.test.ts
test/cf-render-prop.test.ts
test/utils.test.ts
yarn.lock

Ensure valid module names for any given input string.
Fixes #11

fix(export): module name

---

src/utils.ts
test/utils.test.ts

fix(export): escape all special chars in module name

---

src/cf-definitions-builder.ts
src/renderer/cf-render-prop-link.ts
test/cases/case-01.test.ts
test/cases/fixtures/01-input.json
test/cases/fixtures/01-output.txt

Ensure a specific type for any field.

fix(output): no "any" return type

---

src/cf-property-imports.ts
test/cf-property-imports.test.ts

fixes an issue introduce with #73

fix(imports): linked entries in single file export

---

src/renderer/cf-render-prop-link.ts
src/renderer/render-generic-type.ts
test/cases/fixtures/01-input.json
test/cf-render-prop.test.ts

fix: link entry with no validations

---

.github/workflows/semantic-release.yml
README.md
package.json
src/cf-definitions-builder.ts
src/index.ts
src/renderer/cf-render-prop-array.ts
src/renderer/cf-render-prop-link.ts
test/cf-definitions-builder.test.ts

- remove node (`fs-extra`) dependency for builder

feat(build): build experimental branch

---

src/cf-definitions-builder.ts
test/cf-definitions-builder.test.ts

Both export methods (`toString` and `write`), require to modify the source project.
When re-exporting the output changes depending on the order.
With this fix, re-exporting is possible for both methods.

fix(export): make re-exporting possible

---

.github/workflows/test.yml
README.md
src/cf-definitions-builder.ts
src/renderer/type/base-content-type-renderer.ts
src/renderer/type/content-type-renderer.ts
src/renderer/type/localized-content-type-renderer.ts
test/renderer/type/localized-content-type-renfderer.test.ts

- update readme with description for different renderers
- exclude additional file from string output (only include exported types)

fix(renderer): localized

---

src/types.ts
test/cf-definitions-builder.test.ts
test/renderer/type/content-type-renfderer.test.ts
test/renderer/type/localized-content-type-renfderer.test.ts
yarn.lock

Removing an unused `id` field from our Content Type shape.
I'm not sure why this never popped up before ... 
Fixes https://github.com/contentful-userland/cf-content-types-generator/issues/168

fix: expected content type shape

---

package.json

Move ts-node to devDependencies

---

.husky/pre-commit
.lintstagedrc
package.json
yarn.lock

Since we properly lint and format now, we need to ensure it's executed on every commit

chore: add husky and lint-staged

---

.github/workflows/semantic-release.yml
.github/workflows/test.yml

@wojtekmaj again - successor of yours 🙏

chore: update github actions [NONE]

---

.github/workflows/test.yml
package.json
yarn.lock

We should also check if the project builds on every CI run (especially relevant for dependabot updates)
@wojtekmaj also removed unnecessary deps

chore: run build command on CI [NONE]

---

src/index.ts

Seems like `import` is not working here

fix: contentful-export usage [NONE]

---

test/cf-definitions-builder.test.ts

Noticed while working on other stuff - the title is still not the best, but it's better than before

test: remove stray quote from title

---

README.md
src/commands/index.ts

Adds host parameter to CLI
Fixes: https://github.com/contentful-userland/cf-content-types-generator/issues/312

feat: add host parameter

---

src/renderer/type/v10-content-type-renderer.ts
test/renderer/type/js-doc-renderer.test.ts
test/renderer/type/v10-content-type-renderer.test.ts

Fixes a scenario where response types wrongly expect a locale.

fix: non localised entry type

---

test/cf-definitions-builder.test.ts
test/renderer/type/type-guard-renderer.test.ts

Fixes the test for the change introduces with https://github.com/contentful-userland/cf-content-types-generator/pull/344

fix: tests for typeguard changes

---

src/commands/index.ts
src/renderer/type/index.ts
test/renderer/type/response-type-renderer.test.ts

Exports the ResponseTypeRenderer from the package and updates the imports to import from the new path

fix: export response type renderer

---

README.md
package.json

After moving the project from [contentful-labs](https://github.com/contentful-labs) to [contentful-userland]https://github.com/contentful-userland) we have to relfect the change in code.

fix: repo paths
